### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by drjohnsonjr** [seclerp/rider-efcore#108]
#### Describe the bug

"Update Database" additional arguments are prepended by a " -- ", preventing them from being used.

**To Reproduce**

1. In Rider, go to 'Tools > Entity Framework Core > Update Database'
2. Add '--connection MyConnection' to 'Additional Arguments'
3. Click Preview
5. Preview shows " -- " before the additional parameters: 
> dotnet ef database update --project my.csproj --startup-project my.csproj --context myContext --configuration Debug myBranch -- --connection "MyConnection"

#### Expected behavior

Preview command should not have the additional ' -- ' before the additional parameters.

### Environment (please complete the following information):

- OS: Windows 10
- .NET SDK info (installed ones and version used within Rider): 6.0
- Plugin version: 222.1.0
- Rider version: 2022.2.1

**Comment by seclerp** [comment]
This is not the bug. this is expected behavior, see https://docs.microsoft.com/en-us/ef/core/cli/dotnet#aspnet-core-environment

> Starting in EF Core 5.0, additional arguments can also be passed into Program.CreateHostBuilder allowing you to specify the environment on the command-line:
> `dotnet ef database update -- --environment Production`

In our previous topic, I suggested you temporarily use command-line arguments that will be propagated to your app. In the above example, you could move your configuration string into `appsettings.Development.json` and then provide `--environment Development` inside "Additional arguments" to use it from this file (don't forget to set CopyAlways/CopyNewest to the newly created appsettings file).
