### ISSUE TITLE
Add support for environment in UI

### ISSUE THREAD

**Issue by Morasiu** [seclerp/rider-efcore#131]
I love your plugin. It using EF so much easier!

I have a setup, where we are using `appsettings.local.json` and while using dotnet ef we have to pass `--environment Local` as arguments to the command line. It would be helpful if we can just pass the environment in the UI and UI would save that for future usage!

![image](https://user-images.githubusercontent.com/19236279/206434903-a94bb999-45c3-4376-926b-a44377e4f5aa.png)

**Comment by seclerp** [comment]
After some research regarding this feature request, I came to the conclusion that we should do it, but it should be explicitly enabled.

There will be a new checkbox in the EF Core UI settings section called **"Store sensitive data in a secure store"** that will allow saving "Connection" and "Additional arguments" in a secure store from one dialog into another.

**By default it will be disabled**, so you will need to manually turn the lights.

**Comment by Morasiu** [comment]
That sounds great. It help me manage this so much. Thanks.

Also I have to consider making Local env as default

**Comment by seclerp** [comment]
I will close this one, this feature will be available in the next release in a few days.

**Comment by Morasiu** [comment]
Is it live now? I think I cannot find it

**Comment by seclerp** [comment]
Hey @Morasiu, yes, it is available since 223.1.0. If your connection is not persisted between dialogs, you should enable **"Store sensitive data in a secure store"**.

Please also check that you're using the latest version of the plugin (223.2.0 at that moment).

![image](https://user-images.githubusercontent.com/20597871/209173784-bae0fef8-afde-4846-9c47-f0eaaaab3257.png)
