### ISSUE TITLE
Drop Database Additional Arguments

### ISSUE THREAD

**Issue by ninomartini** [seclerp/rider-efcore#166]
The additional argument adds dashes and extra space when using the "Drop Database" feature in a project with multiple contexts.

![Screenshot 2023-05-12 165016](https://github.com/seclerp/rider-efcore/assets/11136112/d1889541-b64f-479c-aadb-87ff42dfd71d)

**Comment by seclerp** [comment]
This is by design, because "Additional arguments" stands for the arguments list for your startup project, not for the `dotnet ef`.

See https://learn.microsoft.com/en-us/ef/core/cli/dotnet#aspnet-core-environment:

> The `--` token directs `dotnet ef` to treat everything that follows as an argument and not try to parse them as options. Any extra arguments not used by dotnet ef are forwarded to the app.

The context class should be configurable from the dialog itself as a field "DbContext", but seems like it's missing due to a bug, I'll fix it in the next release.

**Comment by ninomartini** [comment]
Thank you for the quick response. I greatly appreciate your hard work on this awesome plugin for Rider.
