### ISSUE TITLE
General: Use .NET CLI that is currently used by solution

### ISSUE THREAD

**Issue by seclerp** [seclerp/rider-efcore#96]
In current behavior, we are using .NET CLI just like simple `dotnet` command from a working directory.

Need to get a path to the currently selected .NET SDK in Rider to obtain the correct `dotnet` CLI path.

Notes:
- `ISolutionToolset.GetDotNetCoreToolset()` should help with that (backend)

**Comment by Johnhersh** [comment]
I'm using the version of .Net that Rider installs in the ~/.dotnet folder. It's also where I installed the ef tool because I'm trying to avoid installing things globally. Ideally this would be in a docker container or something. So I would really like this feature so it works with whatever Rider ships
